stages:          # List of stages for jobs, and their order of execution
  - build
  - upload
  - tag
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/groktech/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_TITLE}"

build:
  stage: build
  image: alpine:latest
  only:
      - main
  script:
      - apk add zip
      - apk add jq
      - VERSION=$(jq -r .version src/specs.json)
      - PACKAGE_NAME="${CI_PROJECT_TITLE}-$VERSION.zip"
      - mkdir packages
      - cd "src"
      - zip ../packages/${PACKAGE_NAME} -r ./*
      - printf "PACKAGE_NAME=%s\nVERSION=%s\n" "$PACKAGE_NAME" "$VERSION" ../build.env
  artifacts:
    paths:
      - ./packages
    reports:
      dotenv: build.env


upload:      
  stage: upload
  image: curlimages/curl:latest
  dependencies:
    - build
  script:
    - |
      echo "uploading to: ${PACKAGE_REGISTRY_URL}/$VERSION/$PACKAGE_NAME"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file packages/$PACKAGE_NAME "${PACKAGE_REGISTRY_URL}/$VERSION/$PACKAGE_NAME"
    - echo "Package successfully uploaded."

tag:
  stage: tag
  image: node
  dependencies:
    - build
  script:
    - > 
      if [ $(git tag -l "$VERSION") ]; then
        echo "Version $VERSION already exists"
      else
        git clone https://gitlab.com/groktech/xtz.node.git
        cd xtz.node
        npm install -g git-credential-envvar
        git config credential.helper envvar
        git config user.name  $GITCREDENTIALUSERNAME
        git config user.email $GITCREDENTIALEMAIL
        git tag $VERSION
        git push
        printf "$VERSION" > ./packages/new_release.txt
      fi

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - build
  script:
    - > 
      if grep "$VERSION" ./packages/new_release.txt; then
        echo "Version $VERSION already exists"
      else
        release-cli create --name "$VERSION" --tag-name $VERSION \
        --assets-link "{\"name\":\"$PACKAGE_NAME\",\"url\":\"${PACKAGE_REGISTRY_URL}/$PACKAGE_NAME\"}"
      fi
