stages:          # List of stages for jobs, and their order of execution
  - build
  - upload
  - release

variables:
  PACKAGE_NAME: ${CI_PROJECT_TITLE}-${CI_COMMIT_TAG}.zip
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/groktech/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_TITLE}/${CI_COMMIT_TAG}"

build:
  stage: build
  image: alpine:latest
  only:
      - main
  script:
      - apk add zip
      - mkdir packages
      - cd "src"
      - zip ../packages/${PACKAGE_NAME} -r ./*
  artifacts:
    paths:
      - ./packages


upload:      
  stage: upload
  image: curlimages/curl:latest
  script:
    - |
      echo "uploading to: ${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file packages/${PACKAGE_NAME} "${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"
    - echo "Package successfully uploaded."

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "$CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${PACKAGE_NAME}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}\"}"
